file(MAKE_DIRECTORY "${BINARY_DIR}")
if(MMIO)
  set(TOP tiny3tpu_cordic_mmio)
  set(TEST cordic_mmio_test.cpp)
  set(EXTRA "${SOURCE_DIR}/hardware/math/tiny3tpu_cordic_mmio.sv")
else()
  set(TOP tiny3tpu_cordic_exp)
  set(TEST cordic_exp_test.cpp)
endif()
execute_process(COMMAND "${VERILATOR}" --cc --exe --build -j 2 -Wno-fatal
  --top-module "${TOP}" --Mdir "${BINARY_DIR}" -CFLAGS -std=c++20
  "${SOURCE_DIR}/hardware/math/tiny3tpu_cordic_exp.sv" ${EXTRA}
  "${SOURCE_DIR}/tests/${TEST}" RESULT_VARIABLE result OUTPUT_FILE "${BINARY_DIR}/build.log" ERROR_FILE "${BINARY_DIR}/build.log")
if(NOT result EQUAL 0)
  file(READ "${BINARY_DIR}/build.log" log)
  message(FATAL_ERROR "${log}")
endif()
execute_process(COMMAND "${BINARY_DIR}/V${TOP}" RESULT_VARIABLE result)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "CORDIC check failed: ${result}")
endif()
