"""Compile the cloth linear FEM force island through JAX affine/QGEMM lowering."""
import sys,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];sys.path[:0]=[str(ROOT),sys.argv[1]]
import numpy as np
import jax.numpy as jnp
from model import Cloth
from tools.jax_affine_lowering import lower_rowwise_affine
c=Cloth(6,3);d=np.asarray(c.model.tri_poses)
mu=float(c.model.tri_ke)/(np.linalg.det(d)*2)
matrix=(d@d.transpose(0,2,1))*mu[:,None,None]
groups=[]
for parity in (0,1):
 group=matrix[parity::2];assert np.allclose(group,group[0],rtol=0,atol=2e-4)
 k=jnp.asarray(group[0])
 # Scalarized arithmetic resembles the upstream broadcast multiply/add island.
 def force(x):
  return jnp.stack((x[:,0]*k[0,0]+x[:,1]*k[1,0],x[:,0]*k[0,1]+x[:,1]*k[1,1]),axis=1)
 groups.append(lower_rowwise_affine(force,len(group)*3,2,ROOT/f'build-cloth/force_group{parity}.json'))
(ROOT/'build-cloth/force_lowering.json').write_text(json.dumps(groups,indent=2))
w=np.asarray([g['weights'] for g in groups],np.int32)
(ROOT/'build-cloth/force_plan.h').write_text('/* Generated by the JAX affine lowering pass. */\nstatic const signed char force_matrix[2][2][2]={'+','.join('{'+','.join('{'+','.join(map(str,row))+'}' for row in mat)+'}' for mat in w)+'};\n')
print(w)
