#!/usr/bin/env python3
"""Export the hardware demo with JAX and emit model/input/reference C arrays."""
import argparse
import json
from pathlib import Path
import subprocess
import sys
ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT))
from tools.jax_export import export_function

def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--out',type=Path,default=ROOT/'build-kc705-jax-demo')
    parser.add_argument('--compiler',type=Path,default=ROOT/'build/tiny3tpu-compile')
    args=parser.parse_args()
    import jax
    import jax.numpy as jnp
    x=jnp.array([[3,-4],[-5,6]],dtype=jnp.int8)
    w=jnp.array([[2,-1,3],[-2,4,1]],dtype=jnp.int8)
    b=jnp.array([17,-23,5],dtype=jnp.int32)
    def model(x):
        return jax.lax.dot_general(x,w,(((1,),(0,)),((),())),preferred_element_type=jnp.int32)+b
    args.out.mkdir(parents=True,exist_ok=True)
    export_function(model,x,args.out/'model.json')
    expected=jax.device_get(model(x)).tolist()
    (args.out/'reference.json').write_text(json.dumps(dict(input=x.tolist(),expected=expected),indent=2)+'\n')
    subprocess.run([str(args.compiler),str(args.out/'model.json'),'-o',str(args.out/'model.t3m'),'--run-input','3,-4,-5,6'],check=True)
    arrays=[('unsigned char','jax_model',(args.out/'model.t3m').read_bytes()),
            ('signed char','jax_input',[int(v) for v in x.reshape(-1)]),
            ('int','jax_expected',[v for row in expected for v in row])]
    (args.out/'jax_demo_model.h').write_text('/* Generated by prepare_synapse32_jax_demo.py. */\n'+''.join(
        'static const '+ctype+' '+name+'[] = {'+','.join(map(str,values))+'};\n'
        for ctype,name,values in arrays))
if __name__=='__main__': main()
